### ISSUE TITLE
FeatureREQUEST: Nur bestimmte Linie anzeigen lassen?

### ISSUE THREAD

**Issue by ArnaudFeld** [eckertj/MVG-Abfahrtsmonitor#2]
Hey,

weiß nicht ob das bei dem script so einfach möglich ist aber wäre es möglich das man zum Beispiel sagt: Zeig mir vom Marienplatz nur die S8 an.
Geht das mit dem vorhanden Script oder müsste man da viel ändern?

Gruß
Arnaud

**Comment by corusm** [comment]
Einfach folgendes in `Zeile 220` schreiben:
```
if (response.departures[i].label.toString() != "S8") { continue }
```

**Comment by ArnaudFeld** [comment]
Ok cool. Hab das Skript jemandem empfohlen und da kam die Frage auf ob man das auch für 2 Linien einstellen kann? Z.B.: S1 und S8.
Oder müsste man zwei Widgets erstellen dafür?

**Comment by corusm** [comment]
Dann in dieselbe Zeile:
```javascript
if (response.departures[i].label.toString() != "S8" && response.departures[i].label.toString() != "S1") { continue }
```

**Comment by ArnaudFeld** [comment]
Danke ☺️ 
Hab ich so weiter gegeben
